site_name: IT Documentation
nav:
  - Home: index.md
  - About: about.md
  - User Guide: 
    - Learn Java: guide/java.md
    - Learn JavaScript: guide/javascript.md
theme: 
  name: readthedocs
  analytics:
  gtag: G-ABC123